import {Dimensions, StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  Navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#242526',
    paddingHorizontal: 5,
  },
  Logo: {
    width: 150,
    height: 60,
    objectFit: 'cover',
  },
  SearchMessengerPlus: {
    flexDirection: 'row',
  },
  BgIcon: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 3,
    width: 35,
    height: 35,
    borderRadius: 20,
  },
  StyleIcon: {},
  IconIcon: {
    color: '#5c5f61',
    fontSize: 20,
  },
  text: {
    fontSize: 42,
    color: 'grey',
  },
  logo: {
    color: 'white',
    fontSize: 35,
    fontWeight: '800',
    margin: 5,
  },
  menuMain: {
    backgroundColor: '#242526',
  },
  menuAddUser: {
    marginHorizontal: 15,
    marginTop: 20,
    backgroundColor: '#3f4142',
    borderRadius: 20,
  },
  menuAddUser_top: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 13,
    // borderBottomWidth: 1,
    // borderBottomColor: 'gray',
  },
  menuAddUser_top_left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  menuAddUser_ava: {
    width: 55,
    height: 55,
    borderRadius: 30,
  },
  menuAddUser_name: {
    color: 'white',
    fontSize: 17,
    fontWeight: '600',
  },
  menuAddUser_top_right: {},
  menuAddUser_icon: {
    fontSize: 30,
    color: 'gray',
  },
  menuAddUser_bottom: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingVertical: 13,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'gray',
  },
  menuAddUser_addnewuser: {
    fontSize: 18,
    fontWeight: '700',
    color: 'lightgray',
  },
  menuLoiTat: {
    paddingLeft: 10,
  },
  menuLoiTat_title: {
    fontSize: 15,
    color: 'white',
    fontWeight: '600',
    marginVertical: 15,
    paddingLeft: 10,
  },
  menuLoiTat_list: {
    marginBottom: 10,
  },
  menuLoiTat_item: {
    width: 80,
    alignItems: 'center',
    marginRight: 10,
    gap: 5,
  },
  menuLoiTat_item_top: {
    position: 'relative',
  },
  menuLoiTat_ava: {
    width: 70,
    height: 70,
    borderRadius: 40,
  },
  menuLoiTat_ava_group: {
    width: 70,
    height: 70,
    borderRadius: 5,
  },
  bg_menuLoiTat_icon: {
    position: 'absolute',
    backgroundColor: '#171717',
    paddingHorizontal: 5,
    paddingVertical: 5.5,
    borderRadius: 20,
    bottom: -5,
    right: -5,
    borderWidth: 1,
    borderColor: 'gray',
  },
  menuLoiTat_icon: {
    color: '#318FF6',
    fontSize: 12,
  },
  menuLoiTat_item_bottom: {},
  menuLoiTat_name: {
    color: 'gray',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 12,
  },
  menuMenu: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 10,
  },
  menuMenu_item: {
    flex: 1,
    flexBasis: '47%',
    marginHorizontal: 5,
    borderRadius: 10,
    backgroundColor: '#3f4142',
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    gap: 5,
  },
  menuMenu_icon: {
    fontSize: 25,
    color: '#1e89e8',
  },
  menuMenu_text: {
    color: 'white',
    fontWeight: '700',
  },
  menuMenu_item_more: {
    backgroundColor: '#3f4142',
    width: '97%',
    paddingVertical: 12,
    marginHorizontal: 5,
    borderRadius: 10,
    marginBottom: 20,
    marginTop: 10,
  },
  menuMenu_item_more_text: {
    textAlign: 'center',
    color: 'white',
    fontSize: 18,
    fontWeight: '800',
  },
  menu_more_list: {
    borderTopWidth: 0.5,
    borderTopColor: 'gray',
    marginBottom: 10,
  },
  menu_more_list_button: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menu_more_list_button_left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  menu_more_list_icon: {
    fontSize: 30,
    color: 'gray',
  },
  menu_more_list_title: {
    fontSize: 16,
    color: 'white',
    fontWeight: '700',
  },
  menu_more_list_button_right: {},
  menu_more_list_icon_drop: {
    fontSize: 20,
    color: 'white',
    marginRight: 5,
  },
  menu_more_items: {
    backgroundColor: '#3f4142',
    marginHorizontal: 10,
    padding: 10,
    borderRadius: 10,
    marginVertical: 3,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  menu_more_items_icon: {
    fontSize: 30,
    color: 'gray',
  },
  menu_more_items_text: {
    fontSize: 16,
    fontWeight: '700',
    color: 'white',
  },
  button_logout: {
    marginBottom: 10,
    marginTop: 15,
  },
  logout_btn: {
    backgroundColor: '#3f4142',
    marginHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 10,
  },
  logout_btn_text: {
    textAlign: 'center',
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
  },
});
export default styles;
