import {Dimensions, StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  Navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#242526',
    paddingHorizontal: 5,
    position: 'relative',
    height: 56.9,
  },
  User_name: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
  },
  name: {
    color: 'white',
    fontSize: 17,
    fontWeight: '800',
    margin: 5,
  },
  arrowdow: {
    color: 'white',
    fontSize: 17,
  },
  SearchMessengerPlus: {
    flexDirection: 'row',
    position: 'absolute',
    right: 0,
  },
  BgIcon: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 3,
    width: 35,
    height: 35,
    borderRadius: 20,
  },
  StyleIcon: {},
  IconIcon: {
    color: '#5c5f61',
    fontSize: 20,
  },
  text: {
    fontSize: 42,
    color: 'grey',
  },
  Notification_Title: {
    backgroundColor: '#242526',
    position: 'relative',
  },
  Notification_Title_Text: {
    color: 'white',
    fontWeight: '700',
    fontSize: 20,
    marginVertical: 5,
    marginLeft: 20,
  },
  Notification_List: {
    backgroundColor: '#242526',
  },
  Notification_Item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 110,
    gap: 10,
    padding: 10,
  },
  Notification_Item_Image: {
    position: 'relative',
  },
  Notification_Item_Image_Image: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: 'white',
  },
  Notification_Item_Image_Icon: {
    position: 'absolute',
    bottom: 7,
    right: -3,
    backgroundColor: '#3B5999',
    paddingHorizontal: 5,
    paddingVertical: 4,
    borderRadius: 20,
  },
  Notification_Item_Image_Icon_Icon: {
    color: 'white',
    fontSize: 20,
  },
  Notification_Item_Content: {
    flex: 1,
    gap: 10,
  },
  Notification_Item_Content_Text: {
    color: 'white',
    fontSize: 15,
    maxHeight: 60,
  },
  Notification_Item_Content_Name: {
    fontWeight: '900',
  },
  Notification_Item_Content_Time: {
    color: 'gray',
    fontSize: 13,
  },
  info_user_anhbia: {
    alignItems: 'center',
  },
  anhbia: {
    width: '100%',
    height: 250,
    objectFit: 'cover',
  },
  overlayy: {
    position: 'absolute',
    height: 250,
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  bg_camera_anhbia: {
    backgroundColor: '#242526',
    position: 'absolute',
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 20,
    bottom: 15,
    right: 10,
  },
  camera_anhbia: {
    fontSize: 18,
    color: 'white',
  },
  addanhbia: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    top: 50,
  },
  iconaddanhbia: {
    color: '#242526',
    fontSize: 14,
  },
  addanhbia_text: {
    color: '#242526',
    fontSize: 14,
    fontWeight: '700',
  },
  info_user_profile: {
    marginTop: -125,
    paddingHorizontal: 10,
  },
  info_user_profile_ava: {
    position: 'relative',
  },
  avatar_profile: {
    width: 180,
    height: 180,
    borderRadius: 100,
    borderWidth: 4,
    borderColor: '#242526',
  },
  bg_camera_avatar_profile: {
    backgroundColor: '#3A3B3C',
    position: 'absolute',
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#242526',
    borderRadius: 20,
    bottom: 5,
    left: 133,
  },
  info_user_profile_name: {
    fontSize: 25,
    color: 'white',
    fontWeight: '900',
    marginLeft: 10,
  },
  info_user_profile_tieusu: {
    fontSize: 15,
    color: 'white',
    fontWeight: '300',
    marginLeft: 10,
  },
  info_user_profile_tieusu1: {
    fontSize: 15,
    color: 'white',
    fontWeight: '300',
    marginLeft: 10,
    marginTop: 5,
  },
  addstory: {
    backgroundColor: '#2374E1',
    borderRadius: 7,
    height: 40,
    marginVertical: 5,
    marginTop: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addstory_text: {
    color: 'white',
    fontSize: 15,
    fontWeight: '700',
  },
  buttonchinhsua3cham: {
    flexDirection: 'row',
    width: '100%',
    gap: 10,
    marginBottom: 5,
  },
  buttonchinhsua3cham1: {
    backgroundColor: '#3A3B3C',
    borderRadius: 7,
    height: 40,
    width: '82%',
    marginVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonchinhsua3cham2: {
    backgroundColor: '#3A3B3C',
    borderRadius: 7,
    height: 40,
    width: '15%',
    marginVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalLine: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: '#242526',
  },
  Line: {
    height: 0.3,
    backgroundColor: 'white',
  },
  baiviettitle_Texttt: {
    marginLeft: 10,
  },
  baiviettitle_Text_Active: {
    color: '#609CDA',
    fontWeight: '700',
    fontSize: 15,
    marginVertical: 7,
    backgroundColor: '#27384F',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
  },
  baiviettitle_Text_Text: {
    color: 'white',
    fontWeight: '700',
    fontSize: 15,
    marginVertical: 7,
    backgroundColor: '#242526',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
  },
  baivietreels: {
    paddingHorizontal: 10,
  },
  chitiet: {
    paddingHorizontal: 10,
  },
  chitiet_title: {
    fontSize: 18,
    color: 'white',
    fontWeight: '800',
    marginLeft: 10,
  },
  chitiet_content: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginTop: 15,
    marginLeft: 12,
  },
  chitiet_icon1: {
    fontSize: 25,
    color: 'gray',
  },
  chitiet_icon: {
    fontSize: 21,
    color: 'gray',
  },
  chitiet_text: {
    fontSize: 15,
    color: 'white',
  },
  editprofile: {
    backgroundColor: '#27384F',
    borderRadius: 7,
    height: 40,
    marginVertical: 5,
    marginHorizontal: 5,
    marginTop: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editprofile_text: {
    color: '#609CDA',
    fontSize: 15,
    fontWeight: '700',
  },
  friend: {
    marginTop: 15,
  },
  friend_top: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  friend_top_number_quantity: {},
  friend_top_number_quantity_title: {
    color: 'white',
    fontSize: 20,
    fontWeight: '700',
  },
  friend_top_number_quantity_text: {
    color: 'gray',
    fontSize: 15,
    fontWeight: '400',
  },
  friend_top_searchFriend: {},
  friend_top_searchFriend_text: {
    color: '#569EF0',
    fontSize: 16,
    fontWeight: '400',
  },
  friend_main: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 10,
  },
  friend_main_item: {
    flex: 1,
    flexBasis: '29%',
    marginHorizontal: 5,
    borderRadius: 10,
    backgroundColor: '#3f4142',
    marginBottom: 10,
  },
  friend_main_item_image: {
    width: '100%',
    height: 110,
    objectFit: 'cover',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  friend_main_item_name: {
    fontSize: 14,
    color: 'white',
    fontWeight: '700',
    marginLeft: 8,
    marginVertical: 8,
  },
  friend_bottom: {
    paddingHorizontal: 10,
  },
  friend_bottom_button: {
    backgroundColor: '#3f4142',
    borderRadius: 7,
    height: 40,
    marginVertical: 5,
    marginHorizontal: 5,
    marginTop: 5,
    marginBottom: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  friend_bottom_button_text: {
    color: 'white',
    fontSize: 15,
    fontWeight: '700',
  },
  baiviettitlee: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  baiviett_titleleft: {
    color: 'white',
    fontSize: 18,
    fontWeight: '800',
  },
  baiviett_titleright: {
    color: '#569EF0',
    fontSize: 16,
    fontWeight: '400',
  },
  newbaiviet: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  avatarbaiviet: {
    width: '15%',
  },
  avatarbaiviet_avatar: {
    width: 45,
    height: 45,
    borderRadius: 50,
  },
  inputbaiviet: {
    width: '70%',
  },
  inputbaiviet_input: {
    backgroundColor: '#555555',
    paddingHorizontal: 15,
    borderRadius: 40,
    height: 45,
    color: 'white',
    fontSize: 15,
  },
  imageaddbaiviet: {
    width: '15%',
  },
  Aimageaddbaiviet_Icon: {
    marginLeft: 10,
    color: '#555555',
    fontSize: 27,
  },
  thuocphimphattructiep: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 20,
    backgroundColor: '#303233',
    paddingVertical: 10,
  },
  thuocphim: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: 'gray',
    paddingHorizontal: 15,
    paddingVertical: 5,
    backgroundColor: '#3f4142',
  },
  thuocphim_Icon: {
    color: '#F23E5C',
    fontSize: 20,
  },
  thuocphim_text: {
    color: 'white',
    fontSize: 13,
    fontWeight: '700',
  },
  phattructiep: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  quanlybaiviet: {
    paddingHorizontal: 20,
  },
  quanlybaivietbutton: {
    backgroundColor: '#3f4142',
    flexDirection: 'row',
    gap: 7,
    borderRadius: 7,
    height: 40,
    marginVertical: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quanlybaiviet_Icon: {
    color: 'white',
    fontSize: 20,
  },
  quanlybaiviet_text: {
    color: 'white',
    fontSize: 14,
    fontWeight: '700',
  },
  baivietlist: {
    backgroundColor: 'black',
  },
  chuyenmuc: {
    backgroundColor: '#242526',
    marginTop: 2,
    marginBottom: -2,
    flexDirection: 'row',
    paddingHorizontal: 13,
    paddingVertical: 8,
    gap: 10,
  },
  chuyenmuclist: {
    backgroundColor: '#3f4142',
    paddingHorizontal: 15,
    paddingVertical: 8,
    flexDirection: 'row',
    marginVertical: 10,
    gap: 8,
    alignItems: 'center',
    borderRadius: 20,
  },
  chuyenmuclist_Icon: {
    fontSize: 20,
    color: 'white',
  },
  chuyenmuclist_text: {
    fontSize: 15,
    color: 'white',
    fontWeight: '700',
  },
});
export default styles;
